from __future__ import annotations
from typing import Protocol,TypeVar,runtime_checkable
K=TypeVar("K"); V=TypeVar("V")
@runtime_checkable
class Cache(Protocol[K,V]):
    async def get(self,key:K)->V|None: ...
    async def set(self,key:K,value:V,ttl:float|None=None)->None: ...
    async def delete(self,key:K)->None: ...
    async def exists(self,key:K)->bool: ...
    async def clear(self)->None: ...
